// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAY17aLemMKQ5zn4tvHdfREyZSOYeG9Nc',
    appId: '1:120204644506:web:79207dcf0d2e9c4e734f23',
    messagingSenderId: '120204644506',
    projectId: 'examendi-c6bfa',
    authDomain: 'examendi-c6bfa.firebaseapp.com',
    storageBucket: 'examendi-c6bfa.appspot.com',
    measurementId: 'G-W44E4QQ1ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuEfO2pi4VMaSgZ4xb3BqJS-ZOw8qb4w',
    appId: '1:120204644506:android:8cac2140f16f358b734f23',
    messagingSenderId: '120204644506',
    projectId: 'examendi-c6bfa',
    storageBucket: 'examendi-c6bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdbFwj31bdNSXOHArGdJ8GXRQfdXKzVpY',
    appId: '1:120204644506:ios:a668130cf6f4736a734f23',
    messagingSenderId: '120204644506',
    projectId: 'examendi-c6bfa',
    storageBucket: 'examendi-c6bfa.appspot.com',
    iosClientId: '120204644506-jctj1q7v4rktmadbuluh9pd3jl8fvfbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.examendi',
  );
}
